In [2]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
b = np.array([a.copy(), a.copy(), a.copy()])

In [4]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
c = np.array([[1,2],[3,4]])
d = np.array([c.copy(), c.copy(), c.copy()])
c, d

(array([[1, 2],
        [3, 4]]), array([[[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]]]))

In [6]:
b[np.arange(3),0:2,0:2] * d[np.arange(3), :, :]

array([[[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]]])

In [7]:
e = b[np.arange(3),0:2,0:2] * d[np.arange(3), :, :]
e

array([[[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]]])

In [9]:
f = np.sum(e)
f

111

In [10]:
b


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
b = np.array([b.copy(), b.copy()
    ])

In [12]:
b

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [13]:
b.shape

(2, 3, 3, 3)

In [14]:
e = b[0, np.arange(3),0:2,0:2] * d[np.arange(3), :, :]

In [15]:
e

array([[[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]]])

In [16]:
d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [17]:
d = np.array([d.copy(), d.copy(), d.copy()])

In [18]:
d

array([[[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]]])

In [19]:
e = b[0, np.arange(3),0:2,0:2] * d[0, np.arange(3), :, :]

In [24]:
e

array([[[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]]])

In [25]:
d[:, np.arange(3)] += np.array([1,2,3])

ValueError: operands could not be broadcast together with shapes (3,3,2,2) (3,) (3,3,2,2) 

In [26]:
d[:, np.arange(3), :, :] += np.array([1,2,3])

ValueError: operands could not be broadcast together with shapes (3,3,2,2) (3,) (3,3,2,2) 

In [27]:
e

array([[[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]],

       [[ 1,  4],
        [12, 20]]])

In [28]:
e.shape


(3, 2, 2)

In [30]:
f = np.tile(e, 2)

In [31]:
np.flatten(f, axis=1
          )

AttributeError: module 'numpy' has no attribute 'flatten'

In [32]:
f
f.flatten()

array([ 1,  4,  1,  4, 12, 20, 12, 20,  1,  4,  1,  4, 12, 20, 12, 20,  1,
        4,  1,  4, 12, 20, 12, 20])

In [33]:
f[:].flatten()

array([ 1,  4,  1,  4, 12, 20, 12, 20,  1,  4,  1,  4, 12, 20, 12, 20,  1,
        4,  1,  4, 12, 20, 12, 20])

In [34]:
f[np.arange(3)].flatten()

array([ 1,  4,  1,  4, 12, 20, 12, 20,  1,  4,  1,  4, 12, 20, 12, 20,  1,
        4,  1,  4, 12, 20, 12, 20])

In [35]:
f[np.arange(3), :].flatten()

array([ 1,  4,  1,  4, 12, 20, 12, 20,  1,  4,  1,  4, 12, 20, 12, 20,  1,
        4,  1,  4, 12, 20, 12, 20])

In [36]:
sudoku = np.array([   
    [2, 8, 7, 1, 6, 5, 9, 4, 3],
    [9, 5, 4, 7, 3, 2, 1, 6, 8],
    [6, 1, 3, 8, 4, 9, 7, 5, 2],
    [8, 7, 9, 6, 5, 1, 2, 3, 4],
    [4, 2, 1, 3, 9, 8, 6, 7, 5],
    [3, 6, 5, 4, 2, 7, 8, 9, 1],
    [1, 9, 8, 5, 7, 3, 4, 2, 6],
    [5, 4, 2, 9, 1, 6, 3, 8, 7],
    [7, 3, 6, 2, 8, 4, 5, 1, 9]
])

In [43]:
shape=(5,5,5,5)
strides=sudoku.itemsize*np.array([9,1,9,1])
sudoku_strided = np.lib.stride_tricks.as_strided(sudoku, shape=shape, strides=strides)

In [44]:
sudoku_strided

array([[[[2, 8, 7, 1, 6],
         [9, 5, 4, 7, 3],
         [6, 1, 3, 8, 4],
         [8, 7, 9, 6, 5],
         [4, 2, 1, 3, 9]],

        [[8, 7, 1, 6, 5],
         [5, 4, 7, 3, 2],
         [1, 3, 8, 4, 9],
         [7, 9, 6, 5, 1],
         [2, 1, 3, 9, 8]],

        [[7, 1, 6, 5, 9],
         [4, 7, 3, 2, 1],
         [3, 8, 4, 9, 7],
         [9, 6, 5, 1, 2],
         [1, 3, 9, 8, 6]],

        [[1, 6, 5, 9, 4],
         [7, 3, 2, 1, 6],
         [8, 4, 9, 7, 5],
         [6, 5, 1, 2, 3],
         [3, 9, 8, 6, 7]],

        [[6, 5, 9, 4, 3],
         [3, 2, 1, 6, 8],
         [4, 9, 7, 5, 2],
         [5, 1, 2, 3, 4],
         [9, 8, 6, 7, 5]]],


       [[[9, 5, 4, 7, 3],
         [6, 1, 3, 8, 4],
         [8, 7, 9, 6, 5],
         [4, 2, 1, 3, 9],
         [3, 6, 5, 4, 2]],

        [[5, 4, 7, 3, 2],
         [1, 3, 8, 4, 9],
         [7, 9, 6, 5, 1],
         [2, 1, 3, 9, 8],
         [6, 5, 4, 2, 7]],

        [[4, 7, 3, 2, 1],
         [3, 8, 4, 9, 7],
         [9, 6, 5, 1, 

In [45]:
strides=sudoku.itemsize*np.array([1,9,1,9])
sudoku_strided = np.transpose(np.lib.stride_tricks.as_strided(sudoku, shape=shape, strides=strides), (1,0,3,2))


In [46]:
sudoku_strided

array([[[[2, 8, 7, 1, 6],
         [9, 5, 4, 7, 3],
         [6, 1, 3, 8, 4],
         [8, 7, 9, 6, 5],
         [4, 2, 1, 3, 9]],

        [[8, 7, 1, 6, 5],
         [5, 4, 7, 3, 2],
         [1, 3, 8, 4, 9],
         [7, 9, 6, 5, 1],
         [2, 1, 3, 9, 8]],

        [[7, 1, 6, 5, 9],
         [4, 7, 3, 2, 1],
         [3, 8, 4, 9, 7],
         [9, 6, 5, 1, 2],
         [1, 3, 9, 8, 6]],

        [[1, 6, 5, 9, 4],
         [7, 3, 2, 1, 6],
         [8, 4, 9, 7, 5],
         [6, 5, 1, 2, 3],
         [3, 9, 8, 6, 7]],

        [[6, 5, 9, 4, 3],
         [3, 2, 1, 6, 8],
         [4, 9, 7, 5, 2],
         [5, 1, 2, 3, 4],
         [9, 8, 6, 7, 5]]],


       [[[9, 5, 4, 7, 3],
         [6, 1, 3, 8, 4],
         [8, 7, 9, 6, 5],
         [4, 2, 1, 3, 9],
         [3, 6, 5, 4, 2]],

        [[5, 4, 7, 3, 2],
         [1, 3, 8, 4, 9],
         [7, 9, 6, 5, 1],
         [2, 1, 3, 9, 8],
         [6, 5, 4, 2, 7]],

        [[4, 7, 3, 2, 1],
         [3, 8, 4, 9, 7],
         [9, 6, 5, 1, 