In [1]:
z = np.zeros((3,3,3,3),dtype=np.int)


NameError: name 'np' is not defined

In [2]:
import numpy as np
z = np.zeros((3,3,3,3),dtype=np.int)
z

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [3]:
z[0,0]=1
z

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [4]:
z[0,1], z[0,2], z[1, 0], z[1,1], z[1,2], z[2,0],z[2,1],z[2,2]=2,3,4,5,6,7,8,9

In [5]:
z

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]],


       [[[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6]]],


       [[[7, 7, 7],
         [7, 7, 7],
         [7, 7, 7]],

        [[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]],

        [[9, 9, 9],
         [9, 9, 9],
         [9, 9, 9]]]])

In [6]:
np.concatenate(z, axis=2)

array([[[1, 1, 1, 4, 4, 4, 7, 7, 7],
        [1, 1, 1, 4, 4, 4, 7, 7, 7],
        [1, 1, 1, 4, 4, 4, 7, 7, 7]],

       [[2, 2, 2, 5, 5, 5, 8, 8, 8],
        [2, 2, 2, 5, 5, 5, 8, 8, 8],
        [2, 2, 2, 5, 5, 5, 8, 8, 8]],

       [[3, 3, 3, 6, 6, 6, 9, 9, 9],
        [3, 3, 3, 6, 6, 6, 9, 9, 9],
        [3, 3, 3, 6, 6, 6, 9, 9, 9]]])

In [7]:
np.concatenate(z, axis=1)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [6, 6, 6],
        [6, 6, 6],
        [6, 6, 6],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

In [9]:
np.concatenate(z, axis=0)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

In [10]:
z

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]],


       [[[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6]]],


       [[[7, 7, 7],
         [7, 7, 7],
         [7, 7, 7]],

        [[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]],

        [[9, 9, 9],
         [9, 9, 9],
         [9, 9, 9]]]])

In [11]:
a = z[0,0
    ]

In [12]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.concatenate(a, axis=1)

IndexError: axis 1 out of bounds [0, 1)

In [14]:
np.concatenate(a, axis=0)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.concatenate(z, axis=2)

array([[[1, 1, 1, 4, 4, 4, 7, 7, 7],
        [1, 1, 1, 4, 4, 4, 7, 7, 7],
        [1, 1, 1, 4, 4, 4, 7, 7, 7]],

       [[2, 2, 2, 5, 5, 5, 8, 8, 8],
        [2, 2, 2, 5, 5, 5, 8, 8, 8],
        [2, 2, 2, 5, 5, 5, 8, 8, 8]],

       [[3, 3, 3, 6, 6, 6, 9, 9, 9],
        [3, 3, 3, 6, 6, 6, 9, 9, 9],
        [3, 3, 3, 6, 6, 6, 9, 9, 9]]])

In [17]:
np.concatenate(np.concatenate(z, axis=2), axis=1)

array([[1, 1, 1, 4, 4, 4, 7, 7, 7, 2, 2, 2, 5, 5, 5, 8, 8, 8, 3, 3, 3, 6,
        6, 6, 9, 9, 9],
       [1, 1, 1, 4, 4, 4, 7, 7, 7, 2, 2, 2, 5, 5, 5, 8, 8, 8, 3, 3, 3, 6,
        6, 6, 9, 9, 9],
       [1, 1, 1, 4, 4, 4, 7, 7, 7, 2, 2, 2, 5, 5, 5, 8, 8, 8, 3, 3, 3, 6,
        6, 6, 9, 9, 9]])

In [18]:
np.concatenate(np.concatenate(z, axis=2), axis=0)

array([[1, 1, 1, 4, 4, 4, 7, 7, 7],
       [1, 1, 1, 4, 4, 4, 7, 7, 7],
       [1, 1, 1, 4, 4, 4, 7, 7, 7],
       [2, 2, 2, 5, 5, 5, 8, 8, 8],
       [2, 2, 2, 5, 5, 5, 8, 8, 8],
       [2, 2, 2, 5, 5, 5, 8, 8, 8],
       [3, 3, 3, 6, 6, 6, 9, 9, 9],
       [3, 3, 3, 6, 6, 6, 9, 9, 9],
       [3, 3, 3, 6, 6, 6, 9, 9, 9]])

In [19]:
z

array([[[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]],


       [[[4, 4, 4],
         [4, 4, 4],
         [4, 4, 4]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[6, 6, 6],
         [6, 6, 6],
         [6, 6, 6]]],


       [[[7, 7, 7],
         [7, 7, 7],
         [7, 7, 7]],

        [[8, 8, 8],
         [8, 8, 8],
         [8, 8, 8]],

        [[9, 9, 9],
         [9, 9, 9],
         [9, 9, 9]]]])