In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([6,5,4])
c = np.array([2,5,3])
d = np.array([a.copy(), b.copy(), c.copy()])
d

array([[1, 2, 3],
       [6, 5, 4],
       [2, 5, 3]])

In [2]:
e = np.array([d.copy(), d.transpose().copy()])
e

array([[[1, 2, 3],
        [6, 5, 4],
        [2, 5, 3]],

       [[1, 6, 2],
        [2, 5, 5],
        [3, 4, 3]]])

In [3]:
e.max((0))

array([[1, 6, 3],
       [6, 5, 5],
       [3, 5, 3]])

In [4]:
e.max((1,2))

array([6, 6])

In [5]:
f = np.array([e.copy(), e.copy()])
f

array([[[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]],


       [[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]]])

In [6]:
f.shape
f.max((2,3))

array([[6, 6],
       [6, 6]])

In [7]:
f.shape

(2, 2, 3, 3)

In [8]:
f[:,:,1:2,1:2]

array([[[[5]],

        [[5]]],


       [[[5]],

        [[5]]]])

In [9]:
f[:,:,0:2,0:2]

array([[[[1, 2],
         [6, 5]],

        [[1, 6],
         [2, 5]]],


       [[[1, 2],
         [6, 5]],

        [[1, 6],
         [2, 5]]]])

In [10]:
g = np.zeros((2,2,5,5), dtype=np.float32)

In [11]:
g[:,:,1,1] = f[:,:,0:2,0:2].max((2,3))

In [12]:
g

array([[[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  6.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  6.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  6.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  6.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]]], dtype=float32)

In [13]:
f

array([[[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]],


       [[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]]])

In [15]:
f.argmax((3))

array([[[2, 0, 1],
        [1, 1, 1]],

       [[2, 0, 1],
        [1, 1, 1]]])

In [16]:
f.argmax(2)

array([[[1, 1, 1],
        [2, 0, 1]],

       [[1, 1, 1],
        [2, 0, 1]]])

In [17]:
f

array([[[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]],


       [[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]]])

In [18]:
f[(0,1)]

array([[1, 6, 2],
       [2, 5, 5],
       [3, 4, 3]])

In [19]:
f.argmax()

3

In [20]:
f[:,:].argmax()

3

In [21]:
f[np.arange(2),np.arange(2)]

array([[[1, 2, 3],
        [6, 5, 4],
        [2, 5, 3]],

       [[1, 6, 2],
        [2, 5, 5],
        [3, 4, 3]]])

In [22]:
f[np.arange(2),np.arange(2)].argmax()

3

In [23]:
f[1,2].argmax()

IndexError: index 2 is out of bounds for axis 1 with size 2

In [24]:
f[1,1].argmax()

1

In [25]:
f[:,:].argmax((2,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [26]:
f.reshape(2,2,-1)

array([[[1, 2, 3, 6, 5, 4, 2, 5, 3],
        [1, 6, 2, 2, 5, 5, 3, 4, 3]],

       [[1, 2, 3, 6, 5, 4, 2, 5, 3],
        [1, 6, 2, 2, 5, 5, 3, 4, 3]]])

In [30]:
indices= f.reshape(2,2,-1).argmax(2)


In [31]:
f_flattened = f.reshape(2,2,-1)

In [32]:
f_flattened[indices]=0
f

IndexError: index 3 is out of bounds for axis 0 with size 2

In [33]:
f_flattened

array([[[1, 2, 3, 6, 5, 4, 2, 5, 3],
        [1, 6, 2, 2, 5, 5, 3, 4, 3]],

       [[1, 2, 3, 6, 5, 4, 2, 5, 3],
        [1, 6, 2, 2, 5, 5, 3, 4, 3]]])

In [34]:
indices

array([[3, 1],
       [3, 1]])

In [36]:
unraveled_indices = np.unravel_index(indices, (3,3))

In [37]:
f[unraveled_indices] = 

SyntaxError: invalid syntax (<ipython-input-37-1e7ee1875628>, line 1)

In [38]:
f[unraveled_indices]

array([[[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]],


       [[[1, 2, 3],
         [6, 5, 4],
         [2, 5, 3]],

        [[1, 6, 2],
         [2, 5, 5],
         [3, 4, 3]]]])

In [39]:
f[unraveled_indices] = 0

In [41]:
f_flattened[:,:,(3,1,3,1)]=0

In [42]:
f_flattened

array([[[1, 0, 3, 0, 5, 4, 2, 5, 3],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 2, 0, 5, 5, 3, 4, 3]]])

In [43]:
f_flattened[:,:,[0,1,2,3]]=9

In [44]:
f_flattened

array([[[9, 9, 9, 9, 5, 4, 2, 5, 3],
        [9, 9, 9, 9, 0, 0, 0, 0, 0]],

       [[9, 9, 9, 9, 0, 0, 0, 0, 0],
        [9, 9, 9, 9, 5, 5, 3, 4, 3]]])

In [45]:
f_flattened[np.arange(2), np.arange(2), [0,1,2,3]]=7

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (2,) (4,) 

In [46]:
f_flattened[np.arange(2), indices] = 7

IndexError: index 3 is out of bounds for axis 1 with size 2

In [47]:
f_flattened[:, np.arange(2), [0,1]]=7

In [48]:
f_flattened

array([[[7, 9, 9, 9, 5, 4, 2, 5, 3],
        [9, 7, 9, 9, 0, 0, 0, 0, 0]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [9, 7, 9, 9, 5, 5, 3, 4, 3]]])

In [49]:
f_flattened[np.arange(2),[0,1]]=2

In [50]:
f_flattened

array([[[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [9, 7, 9, 9, 0, 0, 0, 0, 0]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]]])

In [54]:
f_flattened[np.arange(2), np.arange(2), [1,2]]=5
f_flattened

array([[[5, 5, 2, 2, 2, 2, 2, 2, 2],
        [9, 7, 9, 9, 0, 0, 0, 0, 0]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [2, 5, 5, 2, 2, 2, 2, 2, 2]]])

In [52]:
f_flattened

array([[[5, 2, 2, 2, 2, 2, 2, 2, 2],
        [9, 7, 9, 9, 0, 0, 0, 0, 0]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [2, 5, 2, 2, 2, 2, 2, 2, 2]]])

In [53]:
f_flattened[np.arange(2), np.arange(2), np.array([0,1,2,3])]=6

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (2,) (4,) 

In [55]:
f_flattened[[0,0,0],[1,1,1]]=3
f_flattened

array([[[5, 5, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [2, 5, 5, 2, 2, 2, 2, 2, 2]]])

In [56]:
f_flattened[[[0,0,0],[1,1,1]]]=6
f_flattened

array([[[5, 5, 2, 2, 2, 2, 2, 2, 2],
        [6, 6, 6, 6, 6, 6, 6, 6, 6]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [2, 5, 5, 2, 2, 2, 2, 2, 2]]])

In [58]:
f_flattened[[0,0,0]]=6
f_flattened

array([[[6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6]],

       [[7, 9, 9, 9, 0, 0, 0, 0, 0],
        [2, 5, 5, 2, 2, 2, 2, 2, 2]]])

In [62]:
f_flattened[(1,1,2)]=99
f_flattened

array([[[ 1,  6,  6,  6,  6,  6,  6,  6,  6],
        [ 6,  6,  6,  6,  6,  6,  6,  6,  6]],

       [[ 7,  9,  9,  9,  0,  0,  0,  0,  0],
        [ 2,  5, 99,  2,  2,  2,  2,  2,  2]]])

In [ ]:
f_flattened[]